
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: univ_invent
      MYSQL_ROOT_PASSWORD: 12345678
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/univ_invent
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 12345678
    depends_on:
      - db

volumes:
  db_data:
